services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    platform: linux/amd64
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  calculadora:
    build: ./backend  # Asegúrate de que esta línea esté correcta
    # Corrección aquí:
    ports:
      - "8000:8000"
    networks:
      - mongo-network
    depends_on:
      - mongo  # Esto asegura que MongoDB inicie primero

  frontend:
    build: ./frontend-app
    ports:
      # Corrección aquí:
      - "3000:3000"
    volumes:
    - ./frontend-app:/app
    - /app/node_modules
    environment:
    - CHOKIDAR_USEPOLLING=true
    depends_on:
    - calculadora
    networks:
    - mongo-network

networks:
  mongo-network:
    driver: bridge